theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  parse_block_html: true
title: Pontinomicon
description: A bridgey nomic
permalink: /:collection/:title

collections:
  lexicon:
    output: true
