theme: jekyll-theme-slate
markdown: kramdown
title: Pontinomicon
description: A bridgey nomic
permalink: /:collection/:title

collections:
  lexicon:
    output: true

kramdown:
  parse_block_html: true
